// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const storeRefreshToken = `-- name: StoreRefreshToken :exec
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    now() AT TIME ZONE 'UTC',
    now() AT TIME ZONE 'UTC',
    $2,
    now() AT TIME ZONE 'UTC' + $3::integer * INTERVAL '1 day'
)
`

type StoreRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
	Days   int32
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, storeRefreshToken, arg.Token, arg.UserID, arg.Days)
	return err
}
